Update test3.yml

diff --git a/.github/workflows/test3.yml b/.github/workflows/test3.yml
--- a/.github/workflows/test3.yml
+++ b/.github/workflows/test3.yml
@@ -43,15 +43,41 @@ jobs:
         id: runners
         env:
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-          SCOPE: ${{ inputs.runner_scope }}
+          INPUT_RUNNER_SCOPE: ${{ inputs.runner_scope }}
+          INPUT_RUNNER_GROUP: ${{ inputs.runner_group }}
         run: |
-          if [ "$SCOPE" = "repo" ]; then
+          # Function to exit the script with a failure message
+          function exit_with_failure() {
+          	echo >&2 "FAILURE: $1"  # Print error message to stderr
+          	exit 1
+          }
+
+          if [ "$INPUT_RUNNER_SCOPE" = "repo" ]; then
             echo "Fetching repo runners"
             gh api /repos/${{ github.repository }}/actions/runners --paginate
             gh api /repos/${{ github.repository }}/actions/runners --paginate > runners.json
+            
           else
+            curl -L \
+            	--fail-with-body \
+            	-o "github-runner-groups.json" \
+            	-H "Accept: application/vnd.github+json" \
+            	-H "Authorization: Bearer ${GH_TOKEN}" \
+            	-H "X-GitHub-Api-Version: 2022-11-28" \
+            	"https://api.github.com/${{ github.repository_owner }}/actions/runner-groups" \
+            	|| exit_with_failure "Failed to get GitHub Runner groups from ${INPUT_RUNNER_SCOPE}:${INPUT_RUNNER_GROUP}!"
+
+            # 
+            MY_GITHUB_RUNNER_GROUP_ID=$(jq -er ".runner_groups[] | select(.name == \"$INPUT_RUNNER_GROUP\") | .id" < "github-runner-groups.json")
+  
+            # Check if MY_GITHUB_RUNNER_GROUP_ID is an integer
+            if [[ ! "$MY_GITHUB_RUNNER_GROUP_ID" =~ ^[0-9]+$ ]]; then
+              exit_with_failure "Failed to get ID of the GitHub runner group!"
+            fi
+
             echo "Fetching org runners"
-            gh api /orgs/${{ github.repository_owner }}/actions/runners --paginate > runners.json
+            # gh api /orgs/${{ github.repository_owner }}/actions/runners --paginate > runners.json
+            gh api /orgs/${{ github.repository_owner }}/actions/runner-groups/${MY_GITHUB_RUNNER_GROUP_ID}/runners --paginate > runners.json
           fi
 
       - name: Build deletion matrix (extract server IDs from labels)
